- hosts: prod
  gather_facts: yes
  become: yes

  roles:
    - role: cloudalchemy.prometheus
      tags: prometheus
      prometheus_scrape_configs:
        - job_name: 'host'
          static_configs:
            - targets: ['localhost:9100']
              labels:
                env: prod
        - job_name: 'app'
          metrics_path: '/dbo/actuator/prometheus'
          static_configs:
            - targets: ['localhost:8080']
              labels:
                env: prod

    - role: cloudalchemy.node_exporter
      tags: node_exporter
      node_exporter_enabled_collectors:
        - processes
        - systemd
        - tcpstat
        - meminfo_numa
        - mountstats
        - logind
        - ksmd

    - role: cloudalchemy.grafana
      tags: grafana
      grafana_security:
        admin_user: admin
        admin_password: P@ssw0rd
      grafana_datasources:
        - name: Prometheus
          type: prometheus
          url: "http://localhost:9090"
          basicAuth: false
          access: proxy
          isDefault: true

  tasks:
    - name: Open port for node_exporter
      tags: node_exporter
      ansible.builtin.command: firewall-cmd --zone=public --permanent --add-port 9100/tcp

    - name: Open port for node_exporter
      tags: prometheus
      ansible.builtin.command: firewall-cmd --zone=public --permanent --add-port 9090/tcp

    - name: Open port for Grafana
      tags: grafana
      ansible.builtin.command: firewall-cmd --zone=public --permanent --add-port 3000/tcp

    - name: Open port for dbo application
      tags: app
      ansible.builtin.command: firewall-cmd --zone=public --permanent --add-port 8080/tcp

    - name: Open port for JMX
      tags: app
      ansible.builtin.command: firewall-cmd --zone=public --permanent --add-port 9999/tcp

    - name: Reload firewall
      tags: node_exporter,prometheus,grafana,app
      ansible.builtin.command: firewall-cmd --reload

    - name: Install dev software
      tags: devsoft
      ansible.builtin.package:
        name:
          - curl
          - git
          - java-1.8.0-openjdk-devel
          - maven
        state: present
        
    - name: Install adm software
      tags: admsoft
      ansible.builtin.package:
        name:
          - net-tools
          - sysstat
        state: present

    - name: Copy Application
      tags: app
      ansible.builtin.copy:
        src: ../bin/dbo-1.0-SNAPSHOT.jar
        dest: /opt/agile-practices-application/target/
        mode: u=rwx,g=rx,o=rx
